#!/usr/bin/env ruby

require_relative 'lib/dist'
require_relative 'lib/inegi'

def print_averages(data, probs)
  quantiles = average_quantiles(data, probs)
  quantiles.each_with_index do |e, i|
    puts '%02i %.0f' % [i + 1, e]
  end
end

DECILES = gen_probs(10)

puts 'Ingresos por hogar'
puts '------------------'
print_averages($ingresos, DECILES)

puts

puts 'Ingresos per cápita'
puts '-------------------'
print_averages($ingresos_pc, DECILES)
